name: form_inputs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
